name: hughesfamily
favicon: null
layout_spectrum: 0.5964477600064129
typography_spectrum: 0.7777740596793592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3751511825248599
  lightness: 0.9400206380523741
  saturation: 0.6223351038061082
  rhythmicContrast: 0.8633207203820348
purpose: []
